#!/bin/bash
#PBS -l select=1:ngpus=1
#PBS -l walltime=00:10:00
#PBS -j oe
#PBS -V 
#PBS -N TestJobLuma

# load modules
module load cuda-toolkit/11.2.0 python/3.9.17 cudnn/8.0.5 gcc/12.2.0

# change directory
#cd ${PBS_O_WORKDIR}
cd "/home/luma/experiments"

echo ${PBS_O_WORKDIR}

nvidia-smi

eval "$(conda shell.bash hook)"
conda activate derm_class

python src/main.py  
#python src/test_libs.py  > output/saida